const allBalenciaga = [
    {
        id: 21,
        title: "Balenciaga",
        src: "https://cdn-images.farfetch-contents.com/13/27/38/32/13273832_21450011_480.jpg",
        price: 8900,
        count: 1,
        isInterest: false,
        description: "Black track trainers",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 22,
        title: "Balenciaga",
        src: "https://cdn-images.farfetch-contents.com/16/11/36/68/16113668_33583824_480.jpg",
        price: 9100,
        count: 1,
        isInterest: false,
        description: "Speed 2.0 Sneakers",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 23,
        title: "Balenciaga",
        src: "https://cdn-images.farfetch-contents.com/17/33/67/00/17336700_37057556_480.jpg",
        price: 9000,
        count: 1,
        isInterest: false,
        description: "Runner Panelled low-top sneakers",
        content: "",
        category: "Men",
    },
    {
        id: 24,
        title: "Balenciaga",
        src: "https://cdn-images.farfetch-contents.com/16/11/36/65/16113665_31978654_480.jpg",
        price: 7400,
        count: 1,
        isInterest: false,
        description: "Speed sock lace-up snakers",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 25,
        title: "Balenciaga",
        src: "https://cdn-images.farfetch-contents.com/16/57/96/12/16579612_33648701_480.jpg",
        price: 9150,
        count: 1,
        isInterest: false,
        description: "Speed 2.0 LT sneakers",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 26,
        title: "Alexander McQueen",
        src: "https://cdn-images.farfetch-contents.com/17/52/57/32/17525732_41149075_480.jpg",
        price: 6000,
        count: 1,
        isInterest: false,
        description: "Suede low-top sneakers",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Women",
    },
    {
        id: 27,
        title: "UNTIT LAB",
        src: "https://cdn-images.farfetch-contents.com/18/76/24/66/18762466_41135752_480.jpg",
        price: 5000,
        count: 1,
        isInterest: false,
        description: "Untitled reel derby shoes",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Women",
    },
    {
        id: 28,
        title: "Balenciaga",
        src: "https://cdn-images.farfetch-contents.com/18/79/85/56/18798556_41037391_480.jpg",
        price: 8000,
        count: 1,
        isInterest: false,
        description: "Track mesh-panel mules",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "women",
    },
    {
        id: 29,
        title: "Balenciaga",
        src: "https://cdn-static.farfetch-contents.com/cms-cm10/caas/v1/media/3686148/data/a819ce3cba74a20e8fdb180e84d583f8/3x4_three-columns/480/data.jpeg",
        price: 7000,
        count: 1,
        isInterest: false,
        description: "Fresh droped sneakers",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Women",
    },
    {
        id: 30,
        title: "Balenciaga",
        src: "https://cdn-images.farfetch-contents.com/17/73/16/64/17731664_40453986_480.jpg",
        price: 8000,
        count: 1,
        isInterest: false,
        description: "Track 3 sneakers",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Women",
    },
    {
        id: 31,
        title: "Balenciaga Kids",
        src: "https://cdn-images.farfetch-contents.com/16/19/36/38/16193638_33044010_480.jpg",
        price: 5000,
        count: 1,
        isInterest: false,
        description: "Tripple lace",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "kids",
    },
    {
        id: 32,
        title: "Balenciaga Kids",
        src: "https://cdn-images.farfetch-contents.com/15/92/34/88/15923488_31940231_480.jpg",
        price: 4000,
        count: 1,
        isInterest: false,
        description: "Speed Lace-up",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "",
    },
    {
        id: 33,
        title: "Balenciaga Kids",
        src: "https://cdn-images.farfetch-contents.com/16/77/68/78/16776878_33192828_480.jpg",
        price: 5500,
        count: 1,
        isInterest: false,
        description: "Tripple S Sneakers",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "kids",
    },
    {
        id: 34,
        title: "Balenciaga Socks",
        src: "https://cdn-images.farfetch-contents.com/13/31/20/68/13312068_14968551_480.jpg",
        price: 4000,
        count: 1,
        isInterest: false,
        description: "Speed socks Sneakers",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "kids",
    },
    {
        id: 35,
        title: "Balenciaga Kids",
        src: "https://cdn-images.farfetch-contents.com/16/91/12/76/16911276_34369762_480.jpg",
        price: 4500,
        count: 1,
        isInterest: false,
        description: "Tripple S sneakers",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "kids",
    },
    {
        id: 36,
        title: "Balenciaga Kids",
        src: "https://cdn-images.farfetch-contents.com/18/50/86/95/18508695_40795654_480.jpg",
        price: 3900,
        count: 1,
        isInterest: false,
        description: "Spees Lt snekers",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "kids",
    },
]

export default allBalenciaga