const allBoots = [
    {
        id: 1,
        title: "",
        src: "",
        price: ,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 2,
        title: "",
        src: "",
        price: ,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 3,
        title: "",
        src: "",
        price: ,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 4,
        title: "",
        src: "",
        price: ,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 5,
        title: "",
        src: "",
        price: ,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 6,
        title: "",
        src: "",
        price: ,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 7,
        title: "",
        src: "",
        price: ,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Women",
    },
    {
        id: 8,
        title: "Puma x Dua Lipa",
        src: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_350,h_350/global/388611/01/sv01/fnd/PNA/fmt/png/PUMA-x-DUA-LIPA-Mayze-Boot-Women's-Shoes",
        price: 3500
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Women",
    },
    {
        id: 9,
        title: "Mayzee Chelsea Suede Boots",
        src: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_350,h_350/global/382829/01/sv01/fnd/PNA/fmt/png/Mayze-Chelsea-Suede-Women's-Boots",
        price: 2400,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Women",
    },
    {
        id: 10,
        title: "",
        src: "",
        price: ,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Women",
    },
    {
        id: 11,
        title: "",
        src: "",
        price: ,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
    {
        id: 12,
        title: "",
        src: "",
        price: ,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
    {
        id: 13,
        title: "",
        src: "",
        price: ,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
    {
        id: 14,
        title: "",
        src: "",
        price: ,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
    {
        id: 15,
        title: "",
        src: "",
        price: ,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
    {
        id: 16,
        title: "",
        src: "",
        price: ,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
]

export default allBoots