const allCrocs = [
    {
        id: 1,
        title: "Balenciaga",
        src: "https://cdn-images.farfetch-contents.com/18/54/70/31/18547031_41090758_480.jpg",
        price: 5000,
        count: 1,
        isInterest: false,
        description: "All over logo-print platform slides",
        content: "",
        category: "Youth",
    },
    {
        id: 2,
        title: "Valentino Garavani",
        src: "https://cdn-images.farfetch-contents.com/18/46/11/20/18461120_40968442_480.jpg",
        price: 8000,
        count: 1,
        isInterest: false,
        description: "Roman stud flat slides",
        content: "",
        category: "Women",
    },
    {
        id: 3,
        title: "Balenciaga",
        src: "https://cdn-images.farfetch-contents.com/18/54/70/37/18547037_40386970_480.jpg",
        price: 5000,
        count: 1,
        isInterest: false,
        description: "X Crocs Pool platform sandles",
        content: "",
        category: "Youth",
    },
    {
        id: 4,
        title: "Versace",
        src: "https://cdn-images.farfetch-contents.com/18/87/30/06/18873006_41086596_480.jpg",
        price: 5000,
        count: 1,
        isInterest: false,
        description: "Grace-print terrycloth platform sandles",
        content: "",
        category: "Women",
    },
    {
        id: 5,
        title: "Balenciaga",
        src: "https://cdn-images.farfetch-contents.com/17/73/20/23/17732023_40010920_480.jpg",
        price: 3000,
        count: 1,
        isInterest: false,
        description: "logo embroidered pool slides",
        content: "",
        category: "",
    },
    {
        id: 6,
        title: "Balenciaga Kids",
        src: "https://cdn-images.farfetch-contents.com/17/72/97/93/17729793_40386285_480.jpg",
        price: 2000,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        content: "",
        category: "",
    },
    {
        id: 7,
        title: "Nike Offcourt",
        src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/e3f0390b-4ae3-4d0b-a8bd-194db860b6ea/offcourt-mens-slides-Xkb8kb.png",
        price: 4000,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Women",
    },
    {
        id: 8,
        title: "Nike Victoria 1",
        src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/e68a11ae-3300-4619-8695-4aca7514a08d/victori-one-mens-slides-vrTGLL.png",
        price: 3500,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Women",
    },
    {
        id: 9,
        title: "RS-Sandles Women",
        src: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_350,h_350/global/381933/02/sv01/fnd/PNA/fmt/png/RS-Sandal-GID-Women's-Sandals",
        price: 2500,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Women",
    },
    // {
    //     id: 10,
    //     title: "",
    //     src: "",
    //     price: ,
    //     count: 1,
    //     isInterest: false,
    //     description: "",
    //     content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
    //     category: "Women",
    // },
    // {
    //     id: 11,
    //     title: "",
    //     src: "",
    //     price: ,
    //     count: 1,
    //     isInterest: false,
    //     description: "",
    //     content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
    //     category: "Kids",
    // },
    // {
    //     id: 12,
    //     title: "",
    //     src: "",
    //     price: ,
    //     count: 1,
    //     isInterest: false,
    //     description: "",
    //     content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
    //     category: "Kids",
    // },
    // {
    //     id: 13,
    //     title: "",
    //     src: "",
    //     price: ,
    //     count: 1,
    //     isInterest: false,
    //     description: "",
    //     content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
    //     category: "Kids",
    // },
    // {
    //     id: 14,
    //     title: "",
    //     src: "",
    //     price: ,
    //     count: 1,
    //     isInterest: false,
    //     description: "",
    //     content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
    //     category: "Kids",
    // },
    // {
    //     id: 15,
    //     title: "",
    //     src: "",
    //     price: ,
    //     count: 1,
    //     isInterest: false,
    //     description: "",
    //     content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
    //     category: "Kids",
    // },
    // {
    //     id: 16,
    //     title: "",
    //     src: "",
    //     price: ,
    //     count: 1,
    //     isInterest: false,
    //     description: "",
    //     content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
    //     category: "Kids",
    // },
]

export default allCrocs