const allNewBalance = [
    {
        id: 1,
        title: "Fresh Foam x 1080",
        src: "https://nb.scene7.com/is/image/NB/m108012w_nb_02_i?$pdpflexf2$&wid=464&hei=464",
        price: 1500,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 2,
        title: "RC30",
        src: "https://nb.scene7.com/is/image/NB/urc30ac_nb_02_i?$pdpflexf2$&wid=464&hei=464",
        price: 900,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 3,
        title: "NewBalance",
        src: "https://nb.scene7.com/is/image/NB/m860g12_nb_02_i?$pdpflexf2$&wid=440&hei=440",
        price: 1200,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 4,
        title: "574 Core",
        src: "https://nb.scene7.com/is/image/NB/ml574evn_nb_02_i?$pdpflexf2$&wid=440&hei=440",
        price: 1500,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 5,
        title: "Cruzv1 Relssue",
        src: "https://nb.scene7.com/is/image/NB/mcrzrwo1_nb_02_i?$pdpflexf2$&wid=440&hei=440",
        price: 1000,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 6,
        title: "Fresh Foam Tempo v2",
        src: "https://nb.scene7.com/is/image/NB/mtmpoln2_nb_02_i?$pdpflexf2$&wid=440&hei=440",
        price: 1300,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 7,
        title: "Fresh Foam X860",
        src: "https://nb.scene7.com/is/image/NB/w860d12_nb_02_i?$pdpflexf2$&wid=440&hei=440",
        price: 1000,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Women",
    },
    {
        id: 8,
        title: "Fresh Foam x880",
        src: "https://nb.scene7.com/is/image/NB/w880m12_nb_02_i?$pdpflexf2$&wid=440&hei=440",
        price: 1300,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Women",
    },
    {
        id: 9,
        title: "574 Core",
        src: "https://nb.scene7.com/is/image/NB/wl574evn_nb_02_i?$pdpflexf2$&wid=440&hei=440",
        price: 1000,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Women",
    },
    {
        id: 10,
        title: "Fresh Foam Roav",
        src: "https://nb.scene7.com/is/image/NB/wroavpg1_nb_02_i?$pdpflexf2$&wid=440&hei=440",
        price: 1700,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Women",
    },
    {
        id: 11,
        title: "Roam v2",
        src: "https://nb.scene7.com/is/image/NB/perovrk2_nb_02_i?$pdpflexf2$&wid=464&hei=464",
        price: 700,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
    {
        id: 12,
        title: "Rave Run v2 Bungee Lace",
        src: "https://nb.scene7.com/is/image/NB/ytravgy2_nb_02_i?$pdpflexf2$&wid=464&hei=464",
        price: 800,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
    {
        id: 13,
        title: "Arishi v2",
        src: "https://nb.scene7.com/is/image/NB/paaricb2_nb_02_i?$pdpflexf2$&wid=464&hei=464",
        price: 600,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
    {
        id: 14,
        title: "Fresh Foam x 880v12",
        src: "https://nb.scene7.com/is/image/NB/gp880m12_nb_02_i?$pdpflexf2$&wid=464&hei=464",
        price: 900,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
    {
        id: 15,
        title: "FuelCore Reveal v3 Boa",
        src: "https://nb.scene7.com/is/image/NB/ptrvlva3_nb_02_i?$pdpflexf2$&wid=440&hei=440",
        price: 800,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
    {
        id: 16,
        title: "680v6 Bungee",
        src: "https://nb.scene7.com/is/image/NB/ya680bp6_nb_02_i?$pdpflexf2$&wid=440&hei=440",
        price: 700,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
]

export default allNewBalance