const allNike = [
    {
        id: 1,
        title: "Air Force 1",
        src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/4f37fca8-6bce-43e7-ad07-f57ae3c13142/air-force-1-07-mens-shoes-5QFp5Z.png",
        price: 1100,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 2,
        title: "Airforce 1",
        src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/94bdb62d-c296-4d6a-ae6b-c54dfe2b4acf/air-force-1-07-lv8-mens-shoes-1C4L8V.png",
        price: 1300,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 3,
        title: "Air Zoom Pegasus",
        src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cc8e8ae1-5e2a-40ac-b8ba-77515d72ecb6/air-zoom-pegasus-39-air-hola-lou-mens-road-running-shoes-d4dvtm.png",
        price: 1400,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 4,
        title: "Air Jordans",
        src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a098a48a-25e6-4b93-84bf-06e684a549f3/air-jordan-1-mid-shoes-3DR8L9.png",
        price: 1500,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 5,
        title: "Nike Air VapourMax",
        src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/ufdvjwizdclhgpygwxsb/air-vapormax-plus-mens-shoes-nC0dzF.png",
        price: 2500,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 6,
        title: "Kyrie Infinite",
        src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/4bf54ea7-c1a6-4b8f-94f9-6f8818962c92/kyrie-infinity-basketball-shoes-LvzsVp.png",
        price: 3000,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 7,
        title: "Nike Free Metcon 4",
        src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/5d032ee1-ba4e-476e-b21d-139696446179/free-metcon-4-womens-training-shoes-pxHVt9.png",
        price: 2000,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Women",
    },
    {
        id: 8,
        title: "Nike Air MAx 270",
        src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/083dbbef-0a96-4db0-9586-566ffab68f48/air-max-270-womens-shoes-Pgb94t.png",
        price: 2500,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Women",
    },
    {
        id: 9,
        title: "Nike Ryz 365",
        src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/6a30f55c-32f1-4480-bfe1-7fa59ae0eed1/ryz-365-2-womens-shoes-LkNlGp.png",
        price: 3500,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Women",
    },
    {
        id: 10,
        title: "Nike Air Max Bella",
        src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/29548494-0eb6-4578-a802-5635c202a570/air-max-bella-tr-5-womens-training-shoes-tLCg4B.png",
        price: 2000,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Women",
    },
    {
        id: 11,
        title: "Nike Huarache Run",
        src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/424652d6-0d64-4e1a-8050-a4c32e690493/huarache-run-big-kids-shoes-9h6372.png",
        price: 1000,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Women",
    },
    {
        id: 12,
        title: "Nike Air Uptempo",
        src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/375eabe2-a240-4be2-b505-63149fc0a478/air-more-uptempo-big-kids-shoes-hxcj2z.png",
        price: 1200,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
    {
        id: 13,
        title: "Nike Air Max 270",
        src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/kncr6f3jysl34ejmk7xp/air-max-270-big-kids-shoes-HbtNX3.png",
        price: 1000,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
    {
        id: 14,
        title: "Nike Cortez Basic",
        src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/shwkni5uxu5zdsvhcea5/cortez-basic-big-kids-shoe-KyTwmzZB.png",
        price: 900,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
    {
        id: 15,
        title: "Nike Aire Vapourmax",
        src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a4dfe12d-5067-4bd3-afa5-c6f77fa7a49e/air-vapormax-2021-fk-big-kids-shoes-dWftsH.png",
        price: 1300,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
    {
        id: 16,
        title: "Airforce 1",
        src: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/1aa3abc4-692e-466b-b985-570a178f25ef/air-force-1-big-kids-shoes-M7mcL9.png",
        price: 2000,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
]

export default allNike