const allPuma = [
    {
        id: 1,
        title: "Speed Cat SHheld",
        src: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_350,h_350/global/387272/02/sv01/fnd/PNA/fmt/png/Speedcat-Shield-SD-Driving-Shoes",
        price: 900,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 2,
        title: "Suede Classic Men",
        src: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_350,h_350/global/374915/01/sv01/fnd/PNA/fmt/png/Suede-Classic-XXI-Men's-Sneakers",
        price: 850,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 3,
        title: "RS-X Galaxy",
        src: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_350,h_350/global/387764/01/sv01/fnd/PNA/fmt/png/RS-X-Galaxy-Sneakers",
        price: 1200,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 4,
        title: "Puma DC Justice Legue",
        src: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_350,h_350/global/385820/01/sv01/fnd/PNA/fmt/png/PUMA-x-DC-JUSTICE-LEAGUE-Superman-RS-Z-Sneakers",
        price: 1200,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 5,
        title: "Puma x Batman",
        src: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_350,h_350/global/383290/01/sv01/fnd/PNA/fmt/png/PUMA-x-BATMAN-RS-X-Sneakers",
        price: 2500,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 6,
        title: "Puma XT Refined",
        src: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_350,h_350/global/195354/04/sv01/fnd/PNA/fmt/png/Pure-XT-Refined-Men's-Training-Shoes",
        price: 1000,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 7,
        title: "Defy Mid Women Training",
        src: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_350,h_350/global/195027/02/sv01/fnd/PNA/fmt/png/Defy-Mid-Women's-Training-Shoes",
        price: 1200,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Women",
    },
    {
        id: 8,
        title: "Cali Dream Terry women",
        src: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_350,h_350/global/388568/02/sv01/fnd/PNA/fmt/png/Cali-Dream-Terry-Women's-Sneakers",
        price: 1200,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Women",
    },
    {
        id: 9,
        title: "Puma x Dua Lipa",
        src: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_350,h_350/global/387294/05/sv01/fnd/PNA/fmt/png/PUMA-x-DUA-LIPA-Mayze-Suede-Women's-Sneakers",
        price: 1400,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Women",
    },
    {
        id: 10,
        title: "Suede Classic Women",
        src: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_350,h_350/global/388373/04/sv01/fnd/PNA/fmt/png/Suede-Classix-Women's-Sneakers",
        price: 1200,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Women",
    },
    {
        id: 11,
        title: "RS-Z Visual effect",
        src: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_350,h_350/global/383153/01/sv01/fnd/PNA/fmt/png/RS-Z-Visual-Effects-Sneakers-JR",
        price: 850,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
    {
        id: 12,
        title: "Puma x Batman",
        src: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_350,h_350/global/385766/01/sv01/fnd/PNA/fmt/png/PUMA-x-BATMAN-Mayze-Catwoman-Sneakers-JR",
        price: 900,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
    {
        id: 13,
        title: "RS-Z Hill camp",
        src: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_350,h_350/global/385624/01/sv01/fnd/PNA/fmt/png/RS-Z-Hill-Camp-Sneakers-JR",
        price: 850,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
    {
        id: 14,
        title: "Mayze wild Sneakers",
        src: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_350,h_350/global/385696/04/sv01/fnd/PNA/fmt/png/Mayze-Wild-Sneakers-JR",
        price: 700,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
    {
        id: 15,
        title: "TRC Blaze Galaxy",
        src: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_350,h_350/global/386003/01/sv01/fnd/PNA/fmt/png/TRC-Blaze-Galaxy-Little-Kids'-Shoes",
        price: 900,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
    {
        id: 16,
        title: "Mayze 90's Prep Sneakers",
        src: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_350,h_350/global/386085/02/sv01/fnd/PNA/fmt/png/Mayze-'90s-Prep-Sneakers-JR",
        price: 700,
        count: 1,
        isInterest: false,
        description: "",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
]

export default allPuma