const allReebok = [
    {
        id: 1,
        title: "ZigWild Trail",
        src: "https://assets.reebok.com/images/w_85,h_85,f_auto,q_auto,fl_lossy,c_fill,g_auto/04c32211b1ef4ab98081aeaf0130e2af_9366/zigwild-trail-6-mens-shoes.jpg",
        price: 1100,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 2,
        title: "Classic Leather Shoes",
        src: "https://assets.reebok.com/images/w_85,h_85,f_auto,q_auto,fl_lossy,c_fill,g_auto/361aab0c115e4249b382add80029a012_9366/classic-leather-shoes.jpg",
        price: 800,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 3,
        title: "Reebok Nano Training",
        src: "https://assets.reebok.com/images/w_85,h_85,f_auto,q_auto,fl_lossy,c_fill,g_auto/cf1f177875c54676a45cadc800f9af16_9366/reebok-nano-x2-mens-training-shoes.jpg",
        price: 1300,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 4,
        title: "Club C Men Shoes",
        src: "https://assets.reebok.com/images/w_85,h_85,f_auto,q_auto,fl_lossy,c_fill,g_auto/7b69fecaec0e42ac9665aa940119519b_9366/club-c-85-mens-shoes.jpg",
        price: 750,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 5,
        title: "Dmx Basketball",
        src: "https://assets.reebok.com/images/w_85,h_85,f_auto,q_auto,fl_lossy,c_fill,g_auto/ab9ea90c5776465485bbae5900f9c539_9366/the-answer-dmx-basketball-shoes.jpg",
        price: 1700,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 6,
        title: "Reebok Lite us",
        src: "https://assets.reebok.com/images/w_303,h_303,f_auto,q_auto,fl_lossy,c_fill,g_auto/8c77fd4bfaa74f70af44ad1f01547f09_9366/reebok-lite-plus-3-mens-running-shoes.jpg",
        price: 1400,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 7,
        title: "Cardi B Classic Leather",
        src: "https://assets.reebok.com/images/w_85,h_85,f_auto,q_auto,fl_lossy,c_fill,g_auto/722583e197cc454f8f38ae970126c0be_9366/cardi-b-classic-leather-v2-womens-shoes.jpg",
        price: 1100,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Women",
    },
    {
        id: 8,
        title: "Club C Double shoes",
        src: "https://assets.reebok.com/images/w_85,h_85,f_auto,q_auto,fl_lossy,c_fill,g_auto/034ef1a9566640ecaa37adda0100f97c_9366/club-c-double-womens-shoes.jpg",
        price: 850,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Women",
    },
    {
        id: 9,
        title: "Cardi B Classic Leather ",
        src: "https://assets.reebok.com/images/w_85,h_85,f_auto,q_auto,fl_lossy,c_fill,g_auto/9f8b3781fce64411b2cfae940149e10f_9366/cardi-b-classic-leather-v2-womens-shoes.jpg",
        price: 1100,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Women",
    },
    {
        id: 10,
        title: "Nato Adventure Women",
        src: "https://assets.reebok.com/images/w_85,h_85,f_auto,q_auto,fl_lossy,c_fill,g_auto/4eca8ae6cbf3451cb71aaebd0090c2bd_9366/nano-x2-tr-adventure-womens-training-shoes.jpg",
        price: 1000,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Women",
    },
    {
        id: 11,
        title: "Classic Leather Shoes",
        src: "https://assets.reebok.com/images/w_85,h_85,f_auto,q_auto,fl_lossy,c_fill,g_auto/3613ebaf6ed24a609818ac63000250a3_9366/classic-leather-shoes---toddler.jpg",
        price: 500,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
    {
        id: 12,
        title: "Durable XT Shoes",
        src: "https://assets.reebok.com/images/w_85,h_85,f_auto,q_auto,fl_lossy,c_fill,g_auto/3861e865e1a1403aa823adcc00f44e9c_9366/durable-xt-shoes---preschool.jpg",
        price: 600,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
    {
        id: 13,
        title: "Weebok Clasp Low Shoes",
        src: "https://assets.reebok.com/images/w_85,h_85,f_auto,q_auto,fl_lossy,c_fill,g_auto/c16e40421b5d4ce097c1ae01001587e4_9366/weebok-clasp-low-shoes---toddler.jpg",
        price: 300,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
    {
        id: 14,
        title: "Club C shoes",
        src: "https://assets.reebok.com/images/w_85,h_85,f_auto,q_auto,fl_lossy,c_fill,g_auto/d70f910e2663467184b2abab015b77d8_9366/club-c-shoes---grade-school.jpg",
        price: 600,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
    {
        id: 15,
        title: "Question Mis Shoes",
        src: "https://assets.reebok.com/images/w_303,h_303,f_auto,q_auto,fl_lossy,c_fill,g_auto/986e9627697a47bf8f3baed20153f1ef_9366/question-mid-shoes---toddler.jpg",
        price: 500,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
    {
        id: 16,
        title: "Classic Leather shoes",
        src: "https://assets.reebok.com/images/w_85,h_85,f_auto,q_auto,fl_lossy,c_fill,g_auto/5a5e2769d90e4329accbad80013a7da1_9366/classic-leather-shoes---grade-school.jpg",
        price: 600,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
]

export default allReebok