const allSkechers = [
    {
        id: 1,
        title: "Skechers Slip-in",
        src: "https://www.skechers.com/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dw0b6d7ad9/images/large/124568_OFWT.jpg?sw=289",
        price: 950,
        count: 1,
        isInterest: false,
        description: "Lovely day",
        content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veniam aut illo, hic nisi amet velit. Necessitatibus, itaque quibusdam.",
        category: "Women",
    },
    {
        id: 2,
        title: "Skechers",
        src: "https://www.skechers.com/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dwc50e571c/images/large/232450_NVY.jpg?sw=289",
        price: 900,
        count: 1,
        isInterest: false,
        description: "Smooth step",
        content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veniam aut illo, hic nisi amet velit. Necessitatibus, itaque quibusdam.",
        category: "Women",
    },
    {
        id: 3,
        title: "Skechers",
        src: "https://www.skechers.com/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dw44489cc3/images/large/129270_NVBL.jpg?sw=289",
        price: 1200,
        count: 1,
        isInterest: false,
        description: "Max Cushioning Hyper Craze Bounce",
        content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veniam aut illo, hic nisi amet velit. Necessitatibus, itaque quibusdam.",
        category: "Women",
    },
    {
        id: 4,
        title: "Skechers",
        src: "https://www.skechers.com/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dw5543d93c/images/large/129271_BKW.jpg?sw=289",
        price: 1000,
        count: 1,
        isInterest: false,
        description: "Skechers Go walk massage fit",
        content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veniam aut illo, hic nisi amet velit. Necessitatibus, itaque quibusdam.",
        category: "Women",
    },
    {
        id: 5,
        title: "Skechers",
        src: "https://www.skechers.com/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dwb0d8ea21/images/large/136950_FUS.jpg?sw=289",
        price: 900,
        count: 1,
        isInterest: false,
        description: "Skechers Massage Fit",
        content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veniam aut illo, hic nisi amet velit. Necessitatibus, itaque quibusdam.",
        category: "Women",
    },
    {
        id: 6,
        title: "Skechers",
        src: "https://www.skechers.com/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dw86347ab5/images/large/216245_BKGY.jpg?sw=289",
        price: 1300,
        count: 1,
        isInterest: false,
        description: "Go walk Workout walker",
        content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veniam aut illo, hic nisi amet velit. Necessitatibus, itaque quibusdam.",
        category: "Men",
    },
    {
        id: 7,
        title: "Skechers",
        src: "https://www.skechers.com/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dw768fd141/images/large/232452_BBK.jpg?sw=289",
        price: 900,
        count: 1,
        isInterest: false,
        description: "Skechers Slip-ins",
        content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veniam aut illo, hic nisi amet velit. Necessitatibus, itaque quibusdam.",
        category: "Men",
    },
    {
        id: 8,
        title: "Skechers",
        src: "https://www.skechers.com/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dwb91d5f92/images/large/232400_SLT.jpg?sw=289",
        price: 900,
        count: 1,
        isInterest: false,
        description: "Skechers Arch Fit",
        content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veniam aut illo, hic nisi amet velit. Necessitatibus, itaque quibusdam.",
        category: "Men",
    },
    {
        id: 9,
        title: "Skechers",
        src: "https://www.skechers.com/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dw38edb716/images/large/232041_BKW.jpg?sw=289",
        price: 950,
        count: 1,
        isInterest: false,
        description: "Skechers Arch Fit - Paradyme",
        content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veniam aut illo, hic nisi amet velit. Necessitatibus, itaque quibusdam.",
        category: "Men",
    },
    {
        id: 10,
        title: "Skechers",
        src: "https://www.skechers.com/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dw1a45e826/images/large/232303_RED.jpg?sw=289",
        price: 800,
        count: 1,
        isInterest: false,
        description: "Skechers Arch Fit - Infinite Cool",
        content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veniam aut illo, hic nisi amet velit. Necessitatibus, itaque quibusdam.",
        category: "Men",
    },
    {
        id: 11,
        title: "Skechers",
        src: "https://www.skechers.com/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dw6c14ba2a/images/large/403843_BKLM.gif?sw=289",
        price: 500,
        count: 1,
        isInterest: false,
        description: "Slip-ins: Hypno-flas",
        content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veniam aut illo, hic nisi amet velit. Necessitatibus, itaque quibusdam.",
        category: "Kids",
    },
    {
        id: 12,
        title: "Skechers",
        src: "https://www.skechers.com/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dw706a9a8f/images/large/406043_RDBK.gif?sw=289",
        price: 650,
        count: 1,
        isInterest: false,
        description: "Ryan world: Flex-flow",
        content: " Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veniam aut illo, hic nisi amet velit. Necessitatibus, itaque quibusdam.",
        category: "Kids",
    },
    {
        id: 13,
        title: "Skechers",
        src: "https://www.skechers.com/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dwde24ba91/images/large/406061_BKMT.gif?sw=289",
        price: 600,
        count: 1,
        isInterest: false,
        description: "Ryan Worlds :Flex Grow",
        content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veniam aut illo, hic nisi amet velit. Necessitatibus, itaque quibusdam.",
        category: "",
    },
    {
        id: 14,
        title: "Skechers",
        src: "https://www.skechers.com/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dw5e4f35cd/images/large/310102_LTBL.jpg?sw=289",
        price: 500,
        count: 1,
        isInterest: false,
        description: "Sport Sparkle Remix",
        content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veniam aut illo, hic nisi amet velit. Necessitatibus, itaque quibusdam.",
        category: "Kids",
    },
    {
        id: 15,
        title: "Skechers",
        src: "https://www.skechers.com/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dw6d0d2925/images/large/400621_RDBK.jpg?sw=289",
        price: 550,
        count: 1,
        isInterest: false,
        description: "Sport Court show stopping",
        content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veniam aut illo, hic nisi amet velit. Necessitatibus, itaque quibusdam.",
        category: "Kids",
    },
    {
        id: 16,
        title: "Skechers",
        src: "https://www.skechers.com/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dwdab19b47/images/large/310100_LIME.gif?sw=289",
        price: 700,
        count: 1,
        isInterest: false,
        description: "S-light Remix",
        content: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veniam aut illo, hic nisi amet velit. Necessitatibus, itaque quibusdam.",
        category: "Kids",
    },
]

export default allSkechers