const allVans = [
    {
        id: 1,
        title: "Vans x",
        src: "https://images.vans.com/is/image/Vans/VN0A5JMPBO5-HERO?hei=494&wid=492&qlt=50&resMode=sharp2&op_sum=0.9,1.0,8,0",
        price: 900,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 2,
        title: "Vans",
        src: "https://images.vans.com/is/image/Vans/VN000EYEW00-HERO?$PLP-IMAGE$",
        price: 600,
        count: 1,
        isInterest: false,
        description: "Slip-On",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 3,
        title: "Vans",
        src: "https://images.vans.com/is/image/Vans/VN000TS9BJ4-HERO?$PLP-IMAGE$",
        price: 800,
        count: 1,
        isInterest: false,
        description: "Canvas Sk8-Hi",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 4,
        title: "Vans",
        src: "https://images.vans.com/is/image/Vans/VN000D3HY28-HERO?$PLP-IMAGE$",
        price: 700,
        count: 1,
        isInterest: false,
        description: "Old school",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 5,
        title: "Vans",
        src: "https://images.vans.com/is/image/Vans/VN0A3VC1068-ALT1?hei=494&wid=492&qlt=50&resMode=sharp2&op_sum=0.9,1.0,8,0",
        price: 700,
        count: 1,
        isInterest: false,
        description: "Custom MonoBoard Slip-On",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Men",
    },
    {
        id: 6,
        title: "",
        src: "https://images.vans.com/is/image/Vans/VN0A3VC1172-HERO?hei=494&wid=492&qlt=50&resMode=sharp2&op_sum=0.9,1.0,8,0",
        price: 900,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Custom",
    },
    {
        id: 7,
        title: "Vans",
        src: "https://images.vans.com/is/image/Vans/VN0A3VC1171-HERO?hei=494&wid=492&qlt=50&resMode=sharp2&op_sum=0.9,1.0,8,0",
        price: 1200,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Custom",
    },
    {
        id: 8,
        title: "Vans",
        src: "https://images.vans.com/is/image/Vans/VN0A5JMPBO5-HERO?$PLP-IMAGE$",
        price: 1000,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Custom",
    },
    {
        id: 9,
        title: "Vans",
        src: "https://images.vans.com/is/image/Vans/VN0A2XSBY09-HERO?$PLP-IMAGE$",
        price: 1200,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Custom",
    },
    {
        id: 10,
        title: "Vans",
        src: "https://images.vans.com/is/image/Vans/VN0A3VC1174-HERO?hei=392&wid=390&qlt=50&resMode=sharp2&op_sum=0.9,1.0,8,0",
        price: 800,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Custom",
    },
    {
        id: 11,
        title: "Vans",
        src: "https://images.vans.com/is/image/Vans/VN0A7Q5P1OJ-ALT1?hei=494&wid=492&qlt=50&resMode=sharp2&op_sum=0.9,1.0,8,0",
        price: 400,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
    {
        id: 12,
        title: "Vans",
        src: "https://images.vans.com/is/image/Vans/VN0A7Q5GARV-HERO?$PLP-IMAGE$",
        price: 500,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
    {
        id: 13,
        title: "Vans",
        src: "https://images.vans.com/is/image/Vans/VN000VHE6BT-HERO?$PLP-IMAGE$",
        price: 400,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
    {
        id: 14,
        title: "Vans",
        src: "https://images.vans.com/is/image/Vans/VN0A4BUTZNI-HERO?hei=494&wid=492&qlt=50&resMode=sharp2&op_sum=0.9,1.0,8,0",
        price: 300,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
    {
        id: 15,
        title: "Vans",
        src: "https://images.vans.com/is/image/Vans/VN0A4BUVZNI-HERO?hei=494&wid=492&qlt=50&resMode=sharp2&op_sum=0.9,1.0,8,0",
        price: 500,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
    {
        id: 16,
        title: "Vans",
        src: "https://images.vans.com/is/image/Vans/VN0A4BVO1OJ-ALT1?hei=494&wid=492&qlt=50&resMode=sharp2&op_sum=0.9,1.0,8,0",
        price: 400,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
    {
        id: 17,
        title: "Vans",
        src: "https://images.vans.com/is/image/Vans/VN0A7Q5FBD9-HERO?hei=494&wid=492&qlt=50&resMode=sharp2&op_sum=0.9,1.0,8,0",
        price: 300,
        count: 1,
        isInterest: false,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
        content: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex ea et tempora iste nulla iure veniam rerum velit sed, mollitia harum dolor eaque nemo dicta totam quos! Voluptatem, rem iure?",
        category: "Kids",
    },
]

export default allVans